/* Extracts real UI straight out of the Subbies prototype so the animatic shows the
   actual product rather than hand-built lookalikes.
     node capture/build-screens.mjs
   Emits capture/proto-screens.js  ->  { PROTO_CSS, SCREENS }
   The prototype is READ-ONLY from here. Nothing is written back to it. */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const PROTO = 'G:/Claude/Subbies/tenderfy-prototype';

/** Return the balanced <div>…</div> subtree that starts at `marker`. */
function slice(html, marker, occurrence = 1) {
  let from = -1;
  for (let i = 0; i < occurrence; i++) from = html.indexOf(marker, from + 1);
  if (from < 0) throw new Error(`marker not found (${occurrence}): ${marker}`);
  let depth = 0, i = from;
  const open = /<div\b/gi, close = /<\/div>/gi;
  while (i < html.length) {
    open.lastIndex = close.lastIndex = i;
    const o = open.exec(html), c = close.exec(html);
    if (!c) throw new Error(`unbalanced from ${marker}`);
    if (o && o.index < c.index) { depth++; i = o.index + 4; }
    else { depth--; i = c.index + 6; if (depth === 0) return html.slice(from, i); }
  }
  throw new Error(`unbalanced from ${marker}`);
}

const page = (p) => readFileSync(join(PROTO, p), 'utf8');

/* v0.4b — the client wants the WHOLE screen in frame, not an isolated panel.
   Every entry below is therefore sliced from the app shell (sidebar + header +
   content), and the page script is carried so JS-rendered content populates. */

/* Which real panel backs each scene. Occurrence picks between repeats. */
const SPEC = [
  /* contractor pages wrap the whole screen in .capp (sidebar + header + content) */
  { key: 'n3',  file: 'contractor/tender-detail.html', marker: '<div class="capp"', needsPageJs: true },
  { key: 'n4',  file: 'contractor/new-request.html',   marker: '<div class="capp"', needsPageJs: true },
  { key: 'n5',  file: 'contractor/settings.html',      marker: '<div class="capp"', needsPageJs: true },
  { key: 'n6',  file: 'contractor/subbies.html',       marker: '<div class="capp"', needsPageJs: true },
  { key: 'n7',  file: 'contractor/build-tender.html',  marker: '<div class="capp"', needsPageJs: true },
  { key: 's9',  file: 'contractor/compare.html',       marker: '<div class="capp"', needsPageJs: true },
  /* subbie pages hide #screen until their shared layout script runs — unhide it */
  { key: 's7',  file: 'subbies/prepare-quote.html',    marker: '<div id="screen"', needsPageJs: true },
  { key: 's3',  file: 'subbies/view-request.html',     marker: '<div id="screen"', needsPageJs: true },
];

const css = page('styles.css')
  .replace(/@import[^;]+;/g, '')          // no network
  .replace(/\/\*[\s\S]*?\*\//g, '');      // trim comments

const screens = {};
const report = [];
for (const s of SPEC) {
  try {
    let frag = slice(page(s.file), s.marker, s.occurrence || 1);
    frag = frag.replace(/<script[\s\S]*?<\/script>/gi, '')   // no page JS inside the film
               .replace(/\son[a-z]+="[^"]*"/gi, '');          // strip inline handlers
    // some panels are rendered by the page's own script (compare's table is empty
    // in static markup) — carry that script through so the panel populates
    frag = frag.replace(/ collapsed/g, '')              // accordions render open, not shut
               .replace(/style="display:none"/g, '');  // subbie shell is hidden until its layout script runs
    if (s.needsPageJs) {
      const inline = [...page(s.file).matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)]
        .map(m => m[1]).join('\n');
      frag += `<script>${inline}<\/script>`;
    }
    screens[s.key] = frag;
    report.push(`  ${s.key.padEnd(4)} ${String(frag.length).padStart(7)} chars  ${s.marker}`);
  } catch (e) {
    report.push(`  ${s.key.padEnd(4)} FAILED  ${s.file}  ${e.message}`);
  }
}

// NB: </script> inside a fragment would close the film's own <script> block —
// break it so the browser never sees a real closing tag.
const esc = (t) => t.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
                    .replace(/<\/script/gi, '<\\/script');
writeFileSync(
  join(process.cwd(), 'capture/proto-screens.js'),
  `/* GENERATED by capture/build-screens.mjs — do not edit by hand.\n` +
  `   Real CSS and markup lifted from ${PROTO}. */\n` +
  `const PROTO_CSS = \`${esc(css)}\`;\n\n` +
  `const SCREENS = {\n` +
  Object.entries(screens).map(([k, v]) => `  ${k}: \`${esc(v)}\``).join(',\n') +
  `\n};\n`
);

console.log(report.join('\n'));
console.log(`\ncss ${css.length} chars · ${Object.keys(screens).length}/${SPEC.length} screens extracted`);
