/* Re-inlines the generated CSS/markup into an already-built animatic, so a
   prototype change only needs:  build-screens.mjs  then  refresh-screens.mjs   */
import { readFileSync, writeFileSync } from 'node:fs';
const FILM = 'animatic.html';
let h = readFileSync(FILM, 'utf8');
const proto = readFileSync('capture/proto-screens.js', 'utf8');
const a = h.indexOf('/* GENERATED by capture/build-screens.mjs');
const b = h.indexOf('\n/* mount the real prototype panel');
if (a < 0 || b < 0) throw new Error('generated block not found — run apply-screens.mjs first');
h = h.slice(0, a) + proto + h.slice(b);
writeFileSync(FILM, h);
console.log(`refreshed: ${(proto.length / 1024).toFixed(0)}KB of real CSS + markup re-inlined`);
